language: cpp
os: linux
dist: xenial

# Instalação de dependências
addons:
  apt:
    update: true
    packages:
      - g++
      - make
      - bison
      - libboost-all-dev
      - flex

# Instalação principal
script:
  - chmod a+x configure
  - ./configure --with-boost=/usr/lib/x86_64-linux-gnu/
  - ls /usr/lib/x86_64-linux-gnu/
  - make --with-boost=/usr/lib/x86_64-linux-gnu/