language: cpp
os: linux
dist: precise

# Instalação de dependências
before_install:
  # - sudo apt update
  - sudo apt install g++ make bison libboost-all-dev flex

# Instalação principal
script:
  - chmod a+x configure
  - ./configure
  - make