language: cpp
os: linux
dist: xenial

# Instalação de dependências
addons:
  apt:
    update: true
    packages:
      - g++
      - make
      - bison
      - libboost-all-dev
      - flex

# Instalação principal
script:
  - chmod a+x configure
  - ./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu/
  - make

deploy:
  provider: releases
  api_key: 973fac7c2f950a6606d5c744a559c474c397a4ca
  file: 
    - "src/rcssserver"
    - "src/rcssclient"
    - "src/rcsoccersim"
  skip_cleanup: true
  on:
    tags: true
