language: cpp
os: linux
dist: xenial

# Instalação de dependências
before_install:
  - sudo apt update
  - sudo apt install g++ make bison libboost-all-dev flex

# Instalação principal
script:
  - chmod a+x configure
  - ./configure
  - make --with-boost=/usr/lib/x86_64-linux-gnu/